-- 1. Create medical_records table
CREATE TABLE IF NOT EXISTS public.medical_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    pet_id TEXT NOT NULL,
    record_type TEXT NOT NULL, -- 'vaccination' or 'vet_appointment'
    vaccine_name TEXT,
    date DATE NOT NULL,
    next_due_date DATE,
    clinic_name TEXT,
    reason TEXT,
    notes TEXT,
    status TEXT DEFAULT 'Completed', -- 'Upcoming', 'Completed', 'Cancelled'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for medical_records
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own medical records"
ON public.medical_records
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 2. Create medical_reports table
CREATE TABLE IF NOT EXISTS public.medical_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    pet_id TEXT NOT NULL,
    title TEXT NOT NULL,
    upload_date DATE NOT NULL,
    report_type TEXT,
    file_url TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for medical_reports
ALTER TABLE public.medical_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own medical reports"
ON public.medical_reports
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 3. Create Storage Bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('medical-reports', 'medical-reports', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
CREATE POLICY "Users can upload their own reports"
ON storage.objects FOR INSERT
WITH CHECK (
    bucket_id = 'medical-reports' 
    AND (auth.uid())::text = (string_to_array(name, '/'))[1]
);

CREATE POLICY "Users can delete their own reports"
ON storage.objects FOR DELETE
USING (
    bucket_id = 'medical-reports' 
    AND (auth.uid())::text = (string_to_array(name, '/'))[1]
);

CREATE POLICY "Users can read their own reports"
ON storage.objects FOR SELECT
USING (
    bucket_id = 'medical-reports' 
    AND (auth.uid())::text = (string_to_array(name, '/'))[1]
);
