-- Create medical_records table
CREATE TABLE public.medical_records (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    pet_id bigint references public.pets(id) on delete cascade,
    record_type varchar,
    vaccine_name varchar,
    date varchar,
    next_due_date varchar,
    clinic_name varchar,
    reason varchar,
    notes text,
    status varchar,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for medical_records
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert their own medical records."
ON public.medical_records FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own medical records."
ON public.medical_records FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own medical records."
ON public.medical_records FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own medical records."
ON public.medical_records FOR DELETE
USING (auth.uid() = user_id);

-- Create medical_reports table
CREATE TABLE public.medical_reports (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    pet_id bigint references public.pets(id) on delete cascade,
    title varchar,
    report_type varchar,
    upload_date varchar,
    notes text,
    file_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for medical_reports
ALTER TABLE public.medical_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert their own medical reports."
ON public.medical_reports FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own medical reports."
ON public.medical_reports FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own medical reports."
ON public.medical_reports FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own medical reports."
ON public.medical_reports FOR DELETE
USING (auth.uid() = user_id);

-- Create storage bucket for medical-reports if it doesn't exist (assuming postgres extension)
INSERT INTO storage.buckets (id, name, public)
VALUES ('medical-reports', 'medical-reports', true)
ON CONFLICT (id) DO NOTHING;

-- RLS for storage bucket
CREATE POLICY "Public Access for medical-reports" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'medical-reports');

CREATE POLICY "Users can upload medical-reports" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'medical-reports' AND auth.uid() = owner);

CREATE POLICY "Users can delete their medical-reports" 
ON storage.objects FOR DELETE 
USING (bucket_id = 'medical-reports' AND auth.uid() = owner);
