-- Add DELETE policy for community_posts
CREATE POLICY "Users can delete own community posts" ON public.community_posts FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Create community_comments table
CREATE TABLE IF NOT EXISTS public.community_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES public.community_posts(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  parent_id BIGINT REFERENCES public.community_comments(id) ON DELETE CASCADE,
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  payload JSONB
);

ALTER TABLE public.community_comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view community comments" ON public.community_comments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can insert own community comments" ON public.community_comments FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own community comments" ON public.community_comments FOR DELETE TO authenticated USING (auth.uid() = user_id);
